src/component/home/homeStyle.ts, src/page/user/Login.tsx, src/page/user/Register.tsx, src/routes/Router.tsx
* login-signUp 으로 되어있던 로그인, 회원가입의 영문명 통일
* login-register 이름 통일
* 없음
* 없음
=> chore: login-register 이름 통일

.github/workflows/deploy.yml
* CI/CD 설정
* CI/CD 세팅을 위한 yml 파일 생성
* -
* -
=> feat: CI/CD를 위한 yml 파일을 생성한다

.github/workflows/deploy.yml, .github/workflows/qodana_code_quality.yml, src/component/home/homeStyle.ts, src/page/user/Login.tsx, src/page/user/Register.tsx, src/routes/Router.tsx
* release: v0.1.1
* release: v0.1.1
* -
* -
=> release: v0.1.1

.github/workflows/deploy.yml
npm ci 명령어 대신 npm install 명령어를 사용해 의존성 및 패키지를 설치하도록 수정
* 
*
*
*
=> hot-fix: Edit deploy.yml

.github/workflows/deploy.yml
=> feat: add pipeline

.github/workflows/deploy.yml
=> hot-fix: add case if package-lock.json is not existed

.github/workflows/deploy.yml
=> hot-fix: add case if package-lock.json is not existed (#24)

.github/workflows/deploy.yml, package.json
=> hot-fix: add test script in package.json

package.json
=> hot-fix: add test script in package.json (#26)

.github/workflows/deploy.yml, package.json
=> hot-fix: add skip test function

.github/workflows/deploy.yml, package.json
=> hot-fix: add skip test function (#28)

.github/workflows/deploy.yml, package.json
=> hot-fix: add build test case

.github/workflows/deploy.yml
* hot-fix: add build test case
* 
*
*
*
=> hot-fix: add build test case (#30)

.github/workflows/deploy.yml, package.json
=> hot-fix: use ci and install command

.github/workflows/deploy.yml
* hot-fix: add build test case
* hot-fix: add build case and use ci and install command
* 
*
*
*
=> hot-fix: use ci and install command (#32)

.github/workflows/deploy.yml, package.json
=> hot-fix: add debugging command

.github/workflows/deploy.yml
* hot-fix: add build test case
* hot-fix: add build case and use ci and install command
* hot-fix: add debugging command
* 
*
*
*
=> hot-fix: add debugging command (#34)

.github/workflows/deploy.yml, package.json
=> hot-fix: 빌드 파일을 찾는 기능 추가

.github/workflows/deploy.yml
* hot-fix: add build test case
* hot-fix: add build case and use ci and install command
* hot-fix: add debugging command
* hot-fix: add new commnad
* 
*
*
*
=> hot-fix: 빌드 파일을 찾는 기능 추가 (#36)

src/api/userApi.ts
*  api 주소 변경을 통일한다.
*api 주소 변경을 통일한다.
* 없음
* 없음
=> refactor: cusomter api 주소를 수정한다

vite.config.ts
=> chore: 변경된 port번호를 수정한다.

src/api/userApi.ts, src/assets/icons/LogoIcon.tsx, src/component/layout/element/MainHeader.tsx, src/component/styles/user/cartStyles.ts, src/page/Home.tsx, src/page/user/Cart.tsx, src/routes/Router.tsx, vite.config.ts
=> release: 0.1.9

src/api/clothesApi.ts, src/component/product/ThreeJsModelViewerLocalTest.tsx, src/component/styles/globalStyle.ts, src/component/styles/home/homeStyle.ts, src/component/styles/products/detailStyles.ts, src/component/styles/products/modelStyles.ts, src/page/Home.tsx, src/page/productDetail/ModelFitting.tsx, src/page/productDetail/ProductDetail.tsx, src/routes/Router.tsx
* 카테고리별 의류 조회를 추가한다.
* 카테고리별 의류 조회를 추가한다.
* three 모델 로컬뷰 페이지를 별도로 구현하고, 기존의 내부에 구현된 스타일을 외부로 분리 시켰다.
* 없음
=> feat: 카테고리별 의류 조회를 추가한다.

eslint.config.js, src/api/clothesApi.ts, src/component/hook/useRegisterClothesForm.ts, src/component/styles/products/modifyStyle.ts, src/component/styles/products/registerStyle.ts, src/component/styles/user/AdminLoginContainer.ts, src/component/styles/user/LoginContainer.tsx, src/page/AdminHome.tsx, src/page/productDetail/ProductModify.tsx, src/page/productDetail/ProductRegister.tsx, src/routes/Router.tsx
=> feat: 상품 등록 기능 및 삭제 기능 추가

src/component/styles/user/chooseAvatarStyles.ts, src/component/styles/user/orderHistoryPageStyles.ts, src/component/styles/user/userModifyStyle.ts, src/page/user/ChooseAvatar.tsx, src/page/user/OrderHistoryPage.tsx, src/routes/Router.tsx
* 아바타 설정하기, 결제 내역 조회 페이지의 화면을 구상했다.
* 없음
* 없음
* 현재 mock data로 작업했기 때문에, API가 필요합니다.
=> feat: 아바타 설정 및 결제 내역 조회 페이지 CSS 구현한다.

src/api/cartApi.ts, src/api/userApi.ts, src/page/productDetail/ProductDetail.tsx, src/page/user/Register.tsx, src/page/user/User.tsx
* 로그아웃 버튼을 추가한다
* 로그아웃 버튼을 추가한다
* 장바구니 추가 api의 불필요한 customer id 전달을 삭제한다
=> feat:로그아웃 버튼을 추가한다

src/api/cartApi.ts, src/api/clothesApi.ts, src/api/userApi.ts, src/component/hook/useRegisterClothesForm.ts, src/component/hook/useRegisterForm.ts, src/page/AdminHome.tsx, src/page/productDetail/ProductDetail.tsx, src/page/productDetail/ProductModify.tsx, src/page/productDetail/ProductRegister.tsx, src/page/user/Register.tsx, src/page/user/User.tsx
=> release: 0.2.0.1

src/page/user/Login.tsx
=> release: 0.2.0.3

src/api/clothesApi.ts, src/component/hook/useRegisterClothesForm.ts, src/component/styles/products/registerStyle.ts, src/page/productDetail/ProductRegister.tsx
=> feat: 상품 등록 기능 예외 처리 완료

src/component/styles/user/cartStyles.ts, src/page/user/Cart.tsx, src/page/user/ChooseAvatar.tsx, src/page/user/Login.tsx, src/page/user/User.tsx
🔍️ 이 PR을 통해 해결하려는 문제가 무엇인가요?
회원 정보 수정 페이지에서 닫기 버튼이 이전 화면으로 돌아가지 않는 문제와 로그인 후 캐릭터 선택 페이지가 표시되지 않는 문제를 해결합니다.
✨ 이 PR에서 핵심적으로 변경된 사항은 무엇일까요?
닫기 버튼을 클릭하면 이전 화면으로 이동하도록 기능을 구현했습니다.
로그인 후, 캐릭터 선택 페이지가 올바르게 표시되도록 수정했습니다.
🔖 핵심 변경 사항 외에 추가적으로 변경된 부분이 있나요?
X
🩺 이 PR에서 테스트 혹은 검증이 필요한 부분이 있을까요?
로그인 후 캐릭터 선택하기 페이지에서 캐릭터 사진이 나오지 않습니다.
=> feat: 닫기 버튼 기능 구현 및 로그인 후 캐릭터 선택 페이지 연결한다.

src/api/clothesApi.ts, src/component/styles/products/detailStyles.ts, src/page/productDetail/ProductDetail.tsx
* 상품 상세 조회를 개선한다
* 사이즈 선택의 기본값을 조회된 사이즈 값의 첫 값으로한다.
* 재고는 10 개 이하인 사이즈만 출력한다
* 재고가 없으면 사이즈 선택 목록에 출력하지 않는다.
* 재고가 모두 없으면 품절 처리한다.
* build 에러 수정했습니다.
=> refactor: 상품 상세 조회를 개선한다

src/api/axiosInstance.ts, src/api/userApi.ts, src/page/productDetail/ProductDetail.tsx, src/page/user/Register.tsx
* 회원가입시 중복 이메일일 경우 alret 창 띄우기
* 장바구니 추가 시 토큰 만료 / 비회원일시 처리
* 회원가입시 중복 이메일일 경우 alret 창 띄우기
* 장바구니 추가 시 토큰 만료 / 비회원일시 처리
* axiosInstance의 에러 메시지가 백엔드 에러 메시지를 보내도록 수정했다.
* 없음
Closes #72 
Closes #73
=> refactor: 회원가입, 장바구니 버튼의 예외처리한다

src/api/userApi.ts, src/component/hook/useRegisterClothesForm.ts, src/page/user/AdminLogin.tsx, src/page/user/User.tsx
* Issue #77 ~ #79 수정
* Issue #77 ~ #79 수정
* 없음.
* 없음.
=> Resolve issues junseoho

src/component/styles/user/userModifyStyle.ts, src/page/user/ChooseAvatar.tsx, src/page/user/User.tsx
* 디자인 및 화면 구성 변경, 캐릭터 선택하기에서 선택한 캐릭터가 나오게끔 구현함.
* 없음.
* 없음.
* 없음.
=> feat: 아바타 선택하기 전체적인 디자인 및 화면 구성을 변경하다.

src/api/clothesApi.ts, src/component/layout/element/AdminHeader.tsx, src/component/styles/globalStyle.ts, src/component/styles/home/adminHomeStyle.ts, src/component/styles/home/homeStyle.ts, src/component/styles/products/detailStyles.ts, src/component/styles/products/registerStyle.ts, src/component/styles/user/AdminLoginContainer.ts, src/component/styles/user/cartStyles.ts, src/component/styles/user/chooseAvatarStyles.ts, src/component/styles/user/loginStyles.ts, src/component/styles/user/orderHistoryPageStyles.ts, src/component/styles/user/userModifyStyle.ts, src/page/AdminHome.tsx, src/page/productDetail/ProductDetail.tsx, src/page/user/AdminLogin.tsx, src/page/user/Cart.tsx, src/page/user/Login.tsx
=> style: 스타일 일괄 수정

src/component/styles/products/detailStyles.ts, src/component/styles/user/cartStyles.ts, src/component/styles/user/loginStyles.ts
=>  release: 0.2.21

.github/workflows/qodana_code_quality.yml, src/component/common/constants.ts, src/component/common/validators.ts, src/component/hook/useRegisterForm.ts, src/component/hook/useUserForm.ts, src/component/styles/user/registerStyles.ts, src/page/Home.tsx, src/page/user/ChooseAvatar.tsx, src/page/user/Login.tsx, src/page/user/Register.tsx, src/page/user/User.tsx, src/routes/Router.tsx
* 회원가입 시 체형 선택 진행
* 회원가입 시 체형 선택 진행
-> 회원 정보 입력 후 체형 선택 시 회원가입 되도록 수정
* 회원 정보 수정 에러 해결
=> refactor: 회원가입 시 체형 선택 진행
